# Generated by Django 3.1.2 on 2020-10-28 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountmodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
