# Generated by Django 3.1.2 on 2020-12-08 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20201118_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.accountgroupmodel'),
        ),
    ]
