# Generated by Django 3.1.2 on 2020-12-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201208_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
