# Generated by Django 3.1.2 on 2020-12-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_accountmodel_is_moderator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_active',
        ),
    ]
