# Generated by Django 3.1.2 on 2020-12-09 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_accountmodel_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountmodel',
            old_name='is_admin',
            new_name='is_enabled',
        ),
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_staff',
        ),
    ]
