# Generated by Django 3.1.2 on 2020-12-09 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20201209_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
