# Generated by Django 3.1.2 on 2020-12-09 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountmodel_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_staff',
        ),
    ]
