# Generated by Django 3.1.2 on 2020-12-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_accountmodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
